### ISSUE TITLE
package.json does not include al necessary files

### ISSUE THREAD

**Issue by NeverBehave** [VincentBel/remark-pangu#20]
```
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module './set-options'
Require stack:
- node_modules/remark-pangu/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/node_modules/remark-pangu/index.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'node_modules/remark-pangu/index.js'
  ]
}
```

Released package
```
➜  remark-pangu ls           
index.js  LICENSE  node_modules  package.json  README.md
```

**Comment by VincentBel** [comment]
Oops, forget to add them to npm...

**Comment by zdcdbk** [comment]
Who can tell me what to do, thank you

`$ hexo s
INFO  Validating config
ERROR {
  err: Error: Cannot find module 'pangu'
  Require stack:
  - D:\bloog\themes\shoka\scripts\renderer\njk.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
      at Function.Module._load (internal/modules/cjs/loader.js:687:27)
      at Module.require (internal/modules/cjs/loader.js:903:19)
      at require (D:\bloog\node_modules\hexo\lib\hexo\index.js:292:23)
      at D:\bloog\themes\shoka\scripts\renderer\njk.js:6:15
      at D:\bloog\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (D:\bloog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\bloog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\bloog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\bloog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\bloog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\bloog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\bloog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\bloog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\bloog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ 'D:\\bloog\\themes\\shoka\\scripts\\renderer\\njk.js' ]
  }
`

**Comment by vincentbel** [comment]
@zdcdbk try deleting your `node_modules` directory and then reinstall dependencies:

```bash
npm install
```

**Comment by zdcdbk** [comment]
> @zdcdbk删除目录，然后重新安装依赖项：`node_modules`
> 
> ```shell
> npm install
> ```

thank you， I got it done with this code `npm install remark-pangu`
